<a href="https://colab.research.google.com/github/christadel27/belajar_github_wave9/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [2]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [3]:
# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [6]:
# Specifying a subset of a DataFrame = Menentukan subset dari data frame

In [4]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 

Row #2:
   temperature  activity  adjusted
2           20         9        11 

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64


# Do the following:

Create an 3x4 (3 rows x 4 columns) pandas DataFrame in which the columns are named Eleanor, Chidi, Tahani, and Jason. Populate each of the 12 cells in the DataFrame with a random integer between 0 and 100, inclusive.

Output the following:

the entire DataFrame
the value in the cell of row #1 of the Eleanor column
Create a fifth column named Janet, which is populated with the row-by-row sums of Tahani and Jason.

To complete this task, it helps to know the NumPy basics covered in the NumPy UltraQuick Tutorial.

In [7]:
# latihan yang kubuat
# Write your code here.
# Create and populate a 3x4 NumPy array.
my_data = np.array([[90, 85, 70, 60], [75, 78, 79, 90], [45, 60, 85, 90,], [78, 80, 89, 88], [75, 65, 90, 95]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

   Eleanor  Chidi  Tahani  Jason
0       90     85      70     60
1       75     78      79     90
2       45     60      85     90
3       78     80      89     88
4       75     65      90     95


Dalam konteks DataFrame pada library seperti Pandas di Python, perbedaan antara referensi (referencing) dan salinan (copy) dapat memiliki dampak signifikan pada hasil yang Anda dapatkan. Mari kita bahas keduanya:

Referensi (Referencing):

Ketika Anda membuat referensi ke DataFrame, Anda membuat nama alternatif untuk DataFrame yang sudah ada. Artinya, Anda tidak membuat salinan baru dari data, tetapi hanya membuat cara lain untuk mengakses data yang sama.
Jika Anda melakukan perubahan pada DataFrame melalui referensi, perubahan tersebut akan tercermin dalam DataFrame asli.
Contoh Referensi:
import pandas as pd

data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df1 = pd.DataFrame(data)

# Membuat referensi ke DataFrame asli
df2 = df1

# Perubahan pada df2 juga mempengaruhi df1
df2['A'][0] = 99
print(df1)

Salinan (Copy):

Saat Anda membuat salinan DataFrame, Anda membuat duplikat data yang terisolasi dari DataFrame asli. Perubahan pada salinan tidak mempengaruhi DataFrame asli, dan sebaliknya.
Pandas menyediakan metode copy() untuk membuat salinan dari DataFrame.
Contoh Salinan:
import pandas as pd

data = {'A': [1, 2, 3], 'B': [4, 5, 6]}
df1 = pd.DataFrame(data)

# Membuat salinan dari DataFrame asli
df2 = df1.copy()

# Perubahan pada df2 tidak mempengaruhi df1
df2['A'][0] = 99
print(df1)
Kapan Menggunakan Referensi atau Salinan:

Referensi: Dapat digunakan jika Anda ingin memiliki dua nama untuk DataFrame yang sama, dan perubahan pada satu nama juga terlihat pada nama lainnya. Berguna untuk menghemat memori dan mempercepat eksekusi jika Anda hanya ingin melihat atau mengakses data yang sama.
Salinan: Berguna ketika Anda ingin bekerja dengan dua dataset yang berbeda dan menghindari perubahan yang tidak diinginkan pada DataFrame asli.

In [8]:
# Create a Python list that holds the names of the four columns.
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

# Create a 3x4 numpy array, each cell populated with a random integer.
my_data = np.random.randint(low=0, high=101, size=(3, 4))

# Create a DataFrame.
df = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(df)

# Print the value in row #1 of the Eleanor column.
print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

# Create a column named Janet whose contents are the sum
# of two other columns.
df['Janet'] = df['Tahani'] + df['Jason']

# Print the enhanced DataFrame
print(df)

   Eleanor  Chidi  Tahani  Jason
0       29     55      92     84
1       67      5      48     28
2       26     22      89      2

Second row of the Eleanor column: 67

   Eleanor  Chidi  Tahani  Jason  Janet
0       29     55      92     84    176
1       67      5      48     28     76
2       26     22      89      2     91


MATERI SELANJUTNYA

In [10]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


Populate arrays with specific numbers
Call *np.array* to create a NumPy array with your own hand-picked values. For example, the following call to np.array creates an 8-element array:

In [11]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [12]:
# To populate an array with all zeroes, call np.zeros. To populate an array with all ones, call np.ones.

In [13]:
zeros_1d = np.zeros(5)
print(zeros_1d)

[0. 0. 0. 0. 0.]


np.zeros adalah fungsi dalam NumPy, sebuah library untuk komputasi numerik di Python, yang digunakan untuk membuat array berisi nol. Fungsi ini memiliki sintaksis berikut:
***shape***: Tuple yang menunjukkan ukuran array yang akan dibuat. Misalnya, (2, 3) akan membuat array dua dimensi dengan 2 baris dan 3 kolom.
***dtype*** (opsional): Tipe data dari elemen-elemen array. Secara default adalah float.
**order** (opsional): Spesifikasi urutan penyimpanan array. 'C' untuk urutan C-style (baris utama), 'F' untuk urutan Fortran-style (kolom utama).

In [14]:
# Membuat array 2D berukuran 3x4 dengan elemen-elemen nol
zeros_2d = np.zeros((3, 4))
print(zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [16]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[72 81 86 66 92 74]


In [17]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.4734291  0.96338167 0.93572091 0.23586492 0.72340169 0.59654733]


In [18]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.4734291  2.96338167 2.93572091 2.23586492 2.72340169 2.59654733]


TEST cara membuat urutan indexs beserta hasilnya

In [3]:
feature = np.arange (6,21) # write your code here
print(feature)
label = (feature *3) + 4   # write your code here
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [4]:
#@title Double-click to see a possible solution to Task 2.

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise
print(label)

[ 1.838328   -1.50383572 -0.13403072  0.21703242  1.68134162 -1.84045388
  0.7535527   0.01614384 -1.8636189   1.6184543  -1.95364436 -0.92433292
 -0.75047081 -0.28526631  0.95922562]
[23.838328   23.49616428 27.86596928 31.21703242 35.68134162 35.15954612
 40.7535527  43.01614384 44.1363811  50.6184543  50.04635564 54.07566708
 57.24952919 60.71473369 64.95922562]


## Tugas 2: Menambahkan Beberapa Kebisingan ke Kumpulan Data

Untuk membuat kumpulan data Anda sedikit lebih realistis, masukkan sedikit gangguan acak ke dalam setiap elemen larik `label` yang telah Anda buat. Agar lebih tepat, ubah setiap nilai yang ditetapkan ke `label` dengan menambahkan nilai titik mengambang acak yang *berbeda* antara -2 dan +2.

Jangan bergantung pada penyiaran. Sebagai gantinya, buatlah array `noise` yang memiliki dimensi yang sama dengan `label`.